services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/alialtaf10/jira-clone.git
    dockerfilePath: Dockerfile
    buildCommand: ''
    startCommand: ''
    autoDeploy: true
